apiVersion: apps/v1
kind: Deployment
metadata:
  name: hccm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hccm
  template:
    metadata:
      labels:
        app: hccm
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: dotfile-secret
      containers:
      - name: hccm
        image: murdochr/hccm:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000

        volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/etc/secret-volume"


      imagePullSecrets:
      - name: myregistry

---
kind: Service
apiVersion: v1
metadata:
  name: hccm
spec:
  selector:
    app: hccm
  ports:
    - port: 8000




---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hollyschildcare.saturdaynightdj.com
spec:
  tls:
    - hosts:
        - hollyschildcare.saturdaynightdj.com
      secretName: example-com-tls
  rules:
    - host: hollyschildcare.saturdaynightdj.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: hccm
                port:
                  number: 8000


