apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80



---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80





---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2.saturdaynightdj.com
spec:
  tls:
    - hosts:
        - app2.saturdaynightdj.com
      secretName: example-com-tls
  rules:
    - host: app2.saturdaynightdj.com
      http:
        paths:
          - pathType: Prefix
            path: /foo
            backend:
              service:
                name: foo-service
                port:
                  number: 8080
          - pathType: Prefix
            path: /bar
            backend:
              service:
                name: nginx-service
                port:
                  number: 80

